name: Testim E2E
on: [push]

jobs:
    run-testimio-cli:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v4
              with:
                node-version: 'lts'
                # You can also change 'lts' to any supported LTS Node.js version.
            - run: npm install -g @testim/testim-cli
            - run: testim --token "${{ secrets.TESTIM_TOKEN }}" --project "yoijPwVILGQrxkAVrr2j" --grid "Testim-Grid"
¢